spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      javax:
        persistence:
          validation:
            mode: none
  datasource:
    url: jdbc:mysql://localhost:3306/blogJava
    username: root
    password: Mes1a3*2
  rabbitmq:
    host: localhost
    port: 5672
    username: mstgnz
    password: mstgnz

