spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      javax:
        persistence:
          validation:
            mode: none
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
  rabbitmq:
    host: localhost
    port: 5672
    username: mstgnz
    password: mstgnz

